---
title: "RDatabaseBUAN6320"
author: "Phanindra"
date: "November 28, 2018"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
dataset2<- read.delim("BUAN6320-DataSet2.txt",header=TRUE,sep="\t",
           dec = ".", fill = TRUE, comment.char = "")
dataset3<-read.delim("BUAN6320-DataSet3.txt",header=TRUE,sep="\t",
           dec = ".", fill = TRUE, comment.char = "")
dataset4<-read.delim("BUAN6320-DataSet4.txt",header=TRUE,sep="\t",
           dec = ".", fill = TRUE, comment.char = "")
dataset2omitted <- na.omit(dataset2)
dataset3omitted <- na.omit(dataset3)
dataset4omitted <- na.omit(dataset4)
#Dataset3 has columns X,X.1,X.2 which have all NA values, SO they have to be removed.
dataset3removedX <- dataset3[,-c(18,19,20)]
dataset3omitted <- na.omit(dataset3removedX)
#Now dataset3 has all the 252 observations which were present initially.
library(dplyr)
vendor <- dataset3omitted %>% 
  dplyr::select(VEND_STREET,VEND_NAME,VEND_STATE,VEND_CITY,VEND_ID,VEND_ZIP)
#Now exporting the vendor file as a CSV file
write.csv(vendor,file="vendor.csv")

#Now finding the customer table as designed 
customer <- dataset2omitted %>% 
  dplyr::select(CUST_CODE,CUST_FNAME,CUST_LNAME,CUST_STREET,CUST_CITY,CUST_STATE,CUST_ZIP,CUST_BALANCE)
write.csv(customer,file="customer.csv")

#Getting the data for brand
brand <- dataset3omitted %>% 
  dplyr::select(BRAND_NAME,BRAND_TYPE,BRAND_ID)
write.csv(brand,file="brand.csv")
#Getting data for product 
product <- dataset3omitted %>% 
  dplyr::select(PROD_SKU,PROD_DESCRIPT,PROD_TYPE,PROD_BASE,PROD_CATEGORY,PROD_PRICE,PROD_QOH,PROD_MIN,BRAND_ID)
write.csv(product,file="product.csv")

##Getting invoice
invoice <- dataset2omitted %>% 
  dplyr::select(INV_NUM,INV_DATE,INV_TOTAL,EMPLOYEE_ID,CUST_CODE)
write.csv(invoice,file="invoice.csv")





##After getting all the csv files, duplicates were removed in excel using remove duplicates in Data tab.
#Getting data for department
Department <- dataset4omitted %>% 
  dplyr :: select ( DEPT_NUM, DEPT_NAME, DEPT_MAIL_BOX, DEPT_PHONE, SUPV_EMP_NUM)
write.csv(Department, file= "Department.csv")

##Getting salary history 
Salary_history <- dataset4omitted %>% 
  dplyr :: select (SAL_FROM,SAL_END,SAL_AMOUNT,EMP_NUM)
write.csv(Salary_history, file= "Salary_history.csv")

##Getting line 
line <- dataset2omitted %>% 
  dplyr :: select (LINE_NUM,LINE_QTY,LINE_PRICE,INV_NUM,PROD_SKU)
write.csv(line, file= "line.csv")

##Supplies 
Supplies <- dataset3omitted %>% 
  dplyr :: select (PROD_SKU,VEND_ID)
write.csv(Supplies,file="supplies.csv")
```


